"""Add missing tables and models

Revision ID: 89f9acc19f6e
Revises: 2a42300bdd32
Create Date: 2025-06-28 02:37:25.154871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89f9acc19f6e'
down_revision = '2a42300bdd32'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
