"""Initial migration with User model

Revision ID: f8a98fd955b0
Revises: 
Create Date: 2025-06-27 18:50:43.716143

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'f8a98fd955b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('phone', sa.String(length=20), nullable=False, comment='Phone number in international format (+7XXXXXXXXXX)'),
    sa.Column('email', sa.String(length=254), nullable=True, comment='Email address (optional)'),
    sa.Column('first_name', sa.String(length=100), nullable=False, comment='First name'),
    sa.Column('last_name', sa.String(length=100), nullable=False, comment='Last name'),
    sa.Column('middle_name', sa.String(length=100), nullable=True, comment='Middle name (optional)'),
    sa.Column('role', sa.Enum('USER', 'DEVELOPER', 'ADMIN', name='userrole'), nullable=False, comment='User role'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Is user active'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='Is phone number verified'),
    sa.Column('avatar_url', sa.String(length=500), nullable=True, comment='Avatar image URL'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
